model_net:
  name: hieramamba
meta:
  trainer_type: TrainerAuxiliary
  evaluator_type: EvaluatorAuxiliary
model:
  early_fusion: false
  text_net:
    name: transformer
    in_dim: 300
    embd_dim: 128
    n_heads: 4
    max_seq_len: 48
    n_layers: 5
    attn_pdrop: 0.0
    proj_pdrop: 0.1
    path_pdrop: 0.1
    use_abs_pe: true
    use_bkgd_token: true
  vid_net:
    name: hieramamba_backbone
    in_dim: 4096
    embd_dim: 256
    n_heads: 4
    max_seq_len: 2304
    arch:
    - 2
    - 0
    - 8
    use_abs_pe: true
    pool_method: mean
    block_type: AnchorMambaPoolingBlockGated
    ffn_ratio: 2
    return_anchor: true
    local_encode: true
    local_encoder_type: transformer
    local_window_size: 5
    local_encode_num_layers: 0
    mamba_headdim: 64
    mamba_dstate: 64
    mamba_expand: 2
    mamba_dconv: 7
    adaptive_anchor: true
    target_keep_ratio: 0.5
    keep_ratio_per_level:
    - 0.5
    - 0.5
    - 0.5
    - 0.5
    - 0.5
    - 0.5
    - 0.5
    - 0.5
    query_boundary_importance: false
    query_modulation: false
  fusion:
    name: xattn
    n_layers: 2
    n_heads: 4
    attn_pdrop: 0.0
    proj_pdrop: 0.1
    path_pdrop: 0.1
    xattn_mode: affine
  cls_head:
    name: cls
    n_layers: 2
    prior_prob: 0.0
  reg_head:
    name: reg
    n_layers: 2
pt_gen:
  regression_range: 4
  sigma: 0.5
train:
  data:
    name: video_centric
    split: train
    anno_file: ./data/tacos/annotations/tacos.json
    vid_feat_dir: ./data/tacos/c3d_features_official
    text_feat_dir: null
    ext_score_dir: null
    tokenizer: glove
    clip_size: 16
    clip_stride: 4
    downsample_rate: 4
    to_fixed_len: false
    crop_ratio:
    - 0.9
    - 1.0
    max_num_text: 1
  batch_size: 4
  num_workers: 4
  epochs: 10
  warmup_epochs: 5
  ema_beta: 0.999
  center_sampling: radius
  center_sampling_radius: 1.5
  loss_norm: 100
  loss_weight: 1.0
  reg_loss: diou
  loss_aux:
    ds_contrast:
      enable: true
      type: ds_contrastive
      contr_type: contr_mp
      weight: 10.0
      radius: 0
      neg_ratio: 4
      gap_ratio: 0.3
      temperature: 0.07
      proj_outdim: 256
      proj_expand: 1.0
      proj_num_layers: 2
      hard_neg: false
      cross_video_neg: false
      acc_mode: legacy_acc
    gt_contrast:
      enable: true
      type: gt_point_contrastive
      contr_type: point_gt_contr_pooled
      weight: 1.0
      neg_ratio: 1.0
      temperature: 0.07
      use_projector: true
      proj_expand: 1.0
      proj_outdim: 256
      proj_num_layers: 2
      span_radius: 1.5
    query_boundary_importance:
      enable: false
  optimizer:
    name: adamw
    lr: 0.001
    weight_decay: 0.05
  clip_grad_norm: 1.0
  scheduler:
    name: multistep
    steps:
    - -1
eval:
  data:
    name: video_centric
    split: test
  ranks:
  - 1
  - 5
  iou_threshs:
  - 0.3
  - 0.5
  pre_nms_topk: 2000
  pre_nms_thresh: 0.001
  seg_len_thresh: 0.1
  max_text_len: 50
  batchify_text_queries: true
  nms:
    mode: soft_nms
    iou_thresh: 0.1
    min_score: 0.001
    max_num_segs: 5
    sigma: 0.9
    voting_thresh: 0.95
log:
  log_interval: 100
  checkpoint_epochs:
  - -1
  - -2
  - -3
